eureka:
  instance:
    hostname: ${vcap.application.urls[0]:localhost}
    non-secure-port: 80
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url: ${vcap.services.eureka.credentials.uri:http://localhost:8761/eureka}