jdoodle:
  clientId: '59f7bf2496f6f86ce6064f65b5caa1ec'
  secret: 'bc39a60cc1336cfbe8a6e65087f0c0cf7cb95839414ba2d2cfa5c104310d452d'
spring:
  profiles:
    active: test
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: dev
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
  config:
    activate:
      on-profile: test
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  logging:
    level:
      org.springframework.data.r2dbc: Debug
  config:
    activate:
      on-profile: prod
